export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
